/**
* Generated by Tu
* Author: Tonni Diaz
*/
import express from 'express';

const router = express.Router();

router.get('/', async function (req, res, next) {
  try {
    res.render("index", {title: "TuTrader backend"})
  } catch (e) {
    console.log(e);
    res.status(500).render("error")
  }
});

export default router;

