/**
* Generated by Tu
* Author: Tonni Diaz
*/

import createError from 'http-errors';
import express from 'express';
import path from 'path';
import cookieParser from 'cookie-parser';
import logger from 'morgan';
import cors from 'cors';
import dotenv from 'dotenv';

import { Bot, TuConfig } from '@cmn/models';
import { addBooksTask, connectMongo, scheduleAllTasks } from '@cmn/utils/funcs4';
import { DEV, setJobs } from '@cmn/utils/constants';
import { captureLogs } from '@cmn/utils/functions2';

/**Routes */
import indexRouter from './routes';
import botsRouter from './routes/bots';
import { crossArbitWsList, initArbitWs, triArbitWsList } from '@cmn/classes/tu-ws';
import { TuArbitWs } from '@cmn/classes/tu';
import { botLog } from '@cmn/utils/bend/functions';
import { addBotJob } from '@cmn/utils/orders/funcs';
import { addBotToArbitWs } from './utils/funcs';
const app = express();

dotenv.config();
// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'pug');
console.log(`\nPID: ${process.pid}\n`);
app.use(cors());
app.use(
  cors({
    origin: '*',
  })
);
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);
app.use('/bots', botsRouter);

// catch 404 and forward to error handler
app.use(function (req, res, next) {
  next(createError(404));
});

// error handler
app.use(function (err, req, res, next) {
  // set locals, only providing error in development
  res.locals.message = err.message;
  res.locals.error = req.app.get('env') === 'development' ? err : {};
  // render the error page
  res.status(err.status || 500);
  res.render('error'); 
});

const main = async () => {
    // CREATE CONFIG IF NONE
    // if (DEV) return

    const activeBots = await Bot.find({ active: true }).exec();
    setJobs([]);
    await initArbitWs()

    for (let bot of activeBots) {
        const triWs : TuArbitWs = triArbitWsList[bot.platform]
        const crossWs : TuArbitWs = crossArbitWsList[bot.platform]

       
        
        if (bot.type == 'arbitrage' ){
            botLog(bot, "INITIALIZING WS...");
            addBotToArbitWs(bot)
        }else{
             await addBotJob(bot);
        }

        // if (bot.orders.length) {
        //     const lastOrder = await Order.findById(
        //         bot.orders[bot.orders.length - 1]
        //     ).exec();
        //     if (
        //         lastOrder &&
        //         lastOrder.side == "sell" &&
        //         !lastOrder.is_closed &&
        //         lastOrder.sell_price != 0
        //     ) {
        //         //await plat.addBot(bot.id, true);
        //     }
        // }
    }

};


const init = async () => { 
    try{ 
        if (!DEV)
        captureLogs({appName: "tu-trader-worker"})
        console.log("WORKER")
await connectMongo(DEV)
        const config = await TuConfig.findOne({}).exec() || new TuConfig()
    await config.save()
    // const r = await localApi().post('/tasks/books', {books: [1,2,3,4]})
    // console.log(r.data)
    // return 
    // if (DEV) return;
    await scheduleAllTasks()
    if (config.fetch_orderbook_enabled)
        addBooksTask(config)
    
    main()
    } 

    
    catch(e){ 
        console.log("Init error", e)
    }
}

init()

export default app;

