 const BYBIT_API_KEY = "IyLUvBn3TgVHz1mbbs",
    BYBIT_API_SECRET = "wxdkVACT3HGs958aWdQhjWlNVYUvvKh9aGmx",
    BYBIT_API_KEY_DEV = "sSEPHGAWzjY6WwlDDN",
    BYBIT_API_SECRET_DEV = "c1DmowNehIKcMyfGIQ1Q6QFP4blRYXt9HLeP";

module.exports = {BYBIT_API_KEY, BYBIT_API_KEY_DEV, BYBIT_API_SECRET_DEV, BYBIT_API_SECRET}
